version: "3.7"

services:
  server:
    container_name: "folks_server"
    restart: unless-stopped
    build: .
    ports:
      - "4000:4000"

  nginx:
    container_name: "nginx"
    image: nginx:mainline-alpine
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - server
